# Generated by Django 6.0.5 on 2026-05-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='third_party_footer_code',
            field=models.TextField(blank=True, help_text='Paste live chat widgets, tracking scripts, and other third-party code that should load near the end of the page.', verbose_name='Before closing body scripts'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='analytics_body_code',
            field=models.TextField(blank=True, help_text='Paste scripts that must appear immediately after <body>, such as the Google Tag Manager noscript iframe.', verbose_name='Opening body scripts'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='analytics_head_code',
            field=models.TextField(blank=True, help_text='Paste scripts that must appear before </head>, such as Google Analytics, verification tags, pixels, or CSS snippets.', verbose_name='Head scripts'),
        ),
    ]
