# Generated by Django 6.0.5 on 2026-05-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesetting_third_party_footer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL. Leave blank to use the current page URL.'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True, help_text='Optional description for social previews.', verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional social preview image for this page.', upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, help_text='Optional title for Facebook, LinkedIn, and other social previews.', max_length=180, verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Optional comma-separated keywords.', max_length=300),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Tell search engines not to follow links on this page.', verbose_name='Nofollow'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Tell search engines not to index this page.', verbose_name='Noindex'),
        ),
        migrations.AddField(
            model_name='page',
            name='structured_data_json',
            field=models.TextField(blank=True, help_text='Paste JSON-LD only. It will be wrapped in an application/ld+json script tag.', verbose_name='Structured data JSON-LD'),
        ),
        migrations.AddField(
            model_name='page',
            name='twitter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='twitter_image',
            field=models.ImageField(blank=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='page',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_og_image',
            field=models.ImageField(blank=True, help_text='Fallback Open Graph/Twitter image.', upload_to='seo/', verbose_name='Default social share image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_seo_description',
            field=models.TextField(blank=True, help_text='Fallback meta description when a page does not define one.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_seo_keywords',
            field=models.CharField(blank=True, help_text='Optional comma-separated fallback keywords.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_seo_title',
            field=models.CharField(blank=True, help_text='Fallback SEO title when a page does not define one.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_url',
            field=models.URLField(blank=True, help_text='Public website URL, for example https://sabertechlogistics.com. Used for canonical and social fallback URLs.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for search results. Recommended length: 140-160 characters.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Browser title and search title. Recommended length: 50-60 characters.', max_length=180),
        ),
    ]
