# Generated by Django 6.0.5 on 2026-05-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0003_page_canonical_url_page_og_description_page_og_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.page',),
        ),
        migrations.CreateModel(
            name='SiteSEO',
            fields=[
            ],
            options={
                'verbose_name': 'Main SEO setting',
                'verbose_name_plural': 'Main SEO settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitesetting',),
        ),
    ]
